# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# Site settings
url: 'https://jeldo.github.com'
baseurl: ''
title: 'Taeyoung Kwak'
description: ''
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

## Gem settings
author: TaeyoungKwak
social: # jekyll-seo-tag > social overrides
  name: Taeyoung kwak # jekyll-seo-tag > real name
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/taeyoung-kwak-561a5b161/
    - https://github.com/jeldo
# Pagination
paginate: 5
paginate_path: blog/page:num

## Jekyll settings
timezone: Asia/Seoul

# Header nav
navigation_header:
  - title: About
    url: /
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Categories
    url: /categories/
  - title: Search
    url: /search/

# Footer nav
navigation_footer:
  - title: Back to top
    # url: '#top'

# Collections
collections:
  posts:
    title: Blog
    output: true
    # description: "Blog desc"
    # feature_text: Welcome to my blog ggg
    # feature_image: "https://picsum.photos/2560/600?image=865"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/taeyoung-kwak/
  GitHub: https://github.com/jeldo
